name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'
version: 2.0.9+9
environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
#  eClassify_Flutter_Project_V:
#    path: lib/eClassify_Flutter_Project_V   # Reference to the copied project if treated as a separate module
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  get_it: ^8.0.3
  file_picker: ^8.1.7
  provider: ^6.0.3
  lottie:
  mime_type:
  google_mobile_ads: ^5.2.0
  hive_ce_flutter:
  hydrated_bloc:
  awesome_notifications: ^0.10.0
  in_app_purchase:
  flutter_stripe:
  flutter_image_compress:
  device_preview:
  app_links:
  firebase_auth:
  country_picker:
  hive_flutter:
  razorpay_flutter:
  image_cropper:
  in_app_review: ^2.0.10
  flick_video_player:
  youtube_player_flutter:
  encrypt:
  pointycastle:
  device_region:
  sms_autofill:
  any_link_preview:
  audioplayers:
  open_filex:
  vibration: ^2.0.1
  record:
  flutter_bloc:
  dio: ^5.7.0
  http: ^1.1.1
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  webview_flutter: ^4.4.4
  flutter_widget_from_html_core: ^0.15.2
  share_plus: ^10.0.0
  photo_view: ^0.14.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  flutter_svg: ^2.0.9
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.2
#  flutter_keyboard_visibility:
#  contacts_service: ^0.6.3
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  flutter_typeahead: ^5.2.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.15.3
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.1.5
  path: ^1.8.3
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  connectivity_plus:
  sign_in_with_apple: ^6.1.4
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  emoji_picker_flutter: ^4.2.0
  just_audio: ^0.9.36
  carousel_slider: ^5.0.0
  webview_flutter_android: ^3.13.2
  webview_flutter_wkwebview: ^3.10.1
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.1
  open_file_plus: ^3.4.1
  flutter_pdfview: ^1.2.7
  readmore: ^3.0.0
  open_file_manager: ^1.0.2
  get_storage: ^2.0.3

  google_fonts: ^6.2.1
  firebase_database: ^11.2.0
  location: ^7.0.0
  package_info_plus: ^8.1.2
  vector_math: ^2.1.4
  uuid: ^4.4.2
  device_info_plus: ^10.1.2
  pinput: ^5.0.0
  animated_text_kit: ^4.2.2
  flutter_map: ^7.0.2
  latlong2: any
  flutter_cache_manager:


  nb_utils: ^7.0.7

  html: ^0.15.4



  speech_to_text: ^7.0.0
  custom_date_range_picker: ^1.1.0

  # FIREBASE

  firebase_crashlytics: ^4.2.0

  firebase_storage: ^12.3.7
  cloud_firestore: ^5.5.1
  firebase_pagination: ^4.1.0

  # FIREBASE MESSAGING

  # STATE MANAGEMENT
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1

  # ICON
  flutter_vector_icons: ^2.0.0




  # OTHER
  flutter_custom_tabs: ^2.1.0
  phonepe_payment_sdk:
  flutter_html: ^3.0.0-beta.2



  # SOCIAL LOGIN

  the_apple_sign_in: ^1.1.1

  # PAYMENT GATEWAYS
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main

  qr_flutter: ^4.1.0 #required for in pix_flutter
  pix_flutter: ^2.2.0

  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main

  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.1.0

  # MAP


  crypto: ^3.0.5 #required for in phonepe




dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/languages/
    - assets/lottie/
    - assets/chat_background/
    - assets/svg/Logo/
    - assets/svg/Illustrators/
    - assets/svg/payment/
    - assets/svg/
    - assets/svg/bottomnav/
    - assets_user_app/images/
    - assets_user_app/audio/
    - assets_user_app/map_style_black.json
    - assets_user_app/dark.json
    - assets_handyman/icons/
    - assets_handyman/
    - assets_handyman/flag/
    - assets_handyman/images/
    - assets_handyman/icons/upi_payment/
    - assets_handyman/lottie/
    - assets_handyman/newDashboard/
  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets_handyman/fonts/Inter-Regular.ttf
