// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLp0vkfYKJcDpEWViE8wrKmNsWfU9a4E',
    appId: '1:1080725742238:android:0e288d16fa19a71e66118f',
    messagingSenderId: '1080725742238',
    projectId: 'e-classify-c90ca',
    storageBucket: 'e-classify-c90ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvtDQ8q5RGs9VsE_4ipy1H-tg-1IvZec',
    appId: '1:1080725742238:ios:8c2a8f69a7f0674f66118f',
    messagingSenderId: '1080725742238',
    projectId: 'e-classify-c90ca',
    storageBucket: 'e-classify-c90ca.firebasestorage.app',
    iosBundleId: 'com.eclassify.wrteam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVagnAeBwe-xhyf4UWGEgvlypUF1tpOc',
    appId: '1:1080725742238:web:a8739e8ed733304f66118f',
    messagingSenderId: '1080725742238',
    projectId: 'e-classify-c90ca',
    authDomain: 'e-classify-c90ca.firebaseapp.com',
    storageBucket: 'e-classify-c90ca.firebasestorage.app',
    measurementId: 'G-7Q8GFZ462P',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSvtDQ8q5RGs9VsE_4ipy1H-tg-1IvZec',
    appId: '1:1080725742238:ios:e113875c2e3c522d66118f',
    messagingSenderId: '1080725742238',
    projectId: 'e-classify-c90ca',
    storageBucket: 'e-classify-c90ca.firebasestorage.app',
    iosBundleId: 'com.eclassify.eclassify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIVagnAeBwe-xhyf4UWGEgvlypUF1tpOc',
    appId: '1:1080725742238:web:87ef8e19af43b96266118f',
    messagingSenderId: '1080725742238',
    projectId: 'e-classify-c90ca',
    authDomain: 'e-classify-c90ca.firebaseapp.com',
    storageBucket: 'e-classify-c90ca.firebasestorage.app',
    measurementId: 'G-G3ZRHGYV0N',
  );

}